import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { BgBox } from "./mainpage/HomePageStyle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Skillwill Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BgBox>{children}</BgBox>
      </body>
    </html>
  );
}
