import "./globals.css";
import { ValuesProvider } from "./context/ValuesContext";
import { Inter } from "next/font/google";
import { BgBox } from "./mainpage/HomePageStyle";
import { Metadata } from "next/types";
import Header from "./components/header";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Skillwill Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ValuesProvider>
        <head>
          <meta name="robots" content="index" />
        </head>
        <body className={inter.className}>
          <Header />
          <BgBox pt={4}>
            <Box className={"container"}>{children}</Box>
          </BgBox>
        </body>
      </ValuesProvider>
    </html>
  );
}
