export const supabaseUrl = "https://qjpwnkassxsukpcwaakr.supabase.co";
export const supabaseKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqcHdua2Fzc3hzdWtwY3dhYWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTE2NDcxNTMsImV4cCI6MjAyNzIyMzE1M30.WmE-4L4Z-zrFIuszbt9SWOe60W6DG6Y-eJ4l0ySopXw";
