export const supabaseUrl = "https://cwdnuevvtnrgjcvaocfl.supabase.co";
export const supabaseKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3ZG51ZXZ2dG5yZ2pjdmFvY2ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTIyMzEzNTUsImV4cCI6MjAyNzgwNzM1NX0.Zx_QtNnt_C7VqL4e7cxfh2YkG8LcPFXyXfe0pq0Lcuw";
